# Generated by Django 4.0.4 on 2022-05-17 05:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poonam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='expected_checkOut_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
